--return {
--  "hrsh7th/nvim-cmp",
--  version = false, -- Last release is way too old
--  event = "InsertEnter",
--  dependencies = {
--    "hrsh7th/cmp-nvim-lsp",
--    "hrsh7th/cmp-buffer",
--    "hrsh7th/cmp-path",
--  },
--  opts = function()
--    vim.api.nvim_set_hl(0, "CmpGhostText", { link = "Comment", default = true })
--    local cmp = require("cmp")
--    local defaults = require("cmp.config.default")()
--    local auto_select = true
--  end
--}
